# Generated by Django 4.1.2 on 2022-10-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contr_name', models.CharField(max_length=50, verbose_name='Название')),
                ('contr_addr', models.CharField(max_length=14, verbose_name='Адрес')),
                ('contr_passwd', models.CharField(max_length=10, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Контроллер',
                'verbose_name_plural': 'Контроллеры',
            },
        ),
        migrations.CreateModel(
            name='Rele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rele_time', models.DateTimeField(auto_now=True, verbose_name='Дата\\Время')),
                ('rele_num', models.IntegerField(verbose_name='Номер реле')),
                ('rele_satus', models.BooleanField(verbose_name='Состояние')),
                ('rele_contr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controllers', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Реле',
                'verbose_name_plural': 'Реле',
            },
        ),
        migrations.CreateModel(
            name='OneWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onewire_time', models.DateTimeField(auto_now=True, verbose_name='Дата\\Время')),
                ('onewire_name', models.CharField(max_length=50, verbose_name='Название')),
                ('onewire_value', models.FloatField(verbose_name='Температура')),
                ('onewire_addr', models.CharField(max_length=20, verbose_name='Адрес')),
                ('onewire_contr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controllers', verbose_name='Контроллер')),
            ],
            options={
                'verbose_name': 'Температура',
                'verbose_name_plural': 'Температура',
            },
        ),
    ]
