# Generated by Django 4.1.2 on 2022-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onewire',
            options={'verbose_name': 'Температуру', 'verbose_name_plural': 'Температура'},
        ),
    ]
