# Generated by Django 4.1.2 on 2022-10-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_onewire_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onewire',
            name='onewire_addr',
        ),
    ]
