# Generated by Django 4.1.2 on 2022-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_onewire_onewire_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rele',
            name='rele_satus',
            field=models.IntegerField(verbose_name='Состояние'),
        ),
    ]
